version: '3.7'

services:
  postgres:
    image: postgres
    container_name: local-postgresql
    env_file: .env
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  data:
