version: "3.7"
services:
  oracle-db:
    container_name: oracle_local
    image: container-registry.oracle.com/database/enterprise:12.2.0.1
    env_file:
      - database.env # configure oracle
    volumes:
      - ./.db:/opt/oracle/oradata # persistent oracle database data.
    ports:
      - 1521:1521
      - 8080:8080
      - 5500:5500
    healthcheck:
      test:
        [
          "CMD",
          "sqlplus",
          "-L",
          "sys/Oracle_123@//localhost:1521/ORCLCDB as sysdba",
          "@healthcheck.sql",
        ]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  .db: # named volumes can be managed easier using docker-compose
