version: "3.7"
services:
  redis:
    container_name: redis_local
    image: "bitnami/redis:latest"
    env_file:
      - .env
    ports:
      - "${REDIS_PORT_NUMBER}:${REDIS_PORT_NUMBER}"
    restart: unless-stopped
    volumes:
      - ./database:/bitnami/redis/data

volumes:
  database: